### ISSUE TITLE
como no va s ausar string temaplate

### ISSUE THREAD

**Issue by tsuchipls** [Awoocado/Chocolat#1]
no vez que tengo miopia csm

**Comment by theMarzon** [comment]
AWANTE ASSEMBLYYYYYYYYYYYYYY

SUUUUUUUUUUUUUUUUUUUUUUU

**Comment by tsuchipls** [comment]
assembly ? que es eso ? yo solo conozco css

**Comment by tsuchipls** [comment]
te lo cierro hdp

**Comment by tsuchipls** [comment]
osea te lo cierro porque css es mejor que assembly

**Comment by theMarzon** [comment]
que hablas trollo>?

**Comment by theMarzon** [comment]
ASSEMBLY ES GOOD
ARRIBA Y MECCORRO DESDE LO ALTOOOO

**Comment by tsuchipls** [comment]
> ASSEMBLY ES GOOD
> 
> ARRIBA Y MECCORRO DESDE LO ALTOOOO

![image](https://user-images.githubusercontent.com/76927919/211135155-2fa7d36f-725a-4b21-bf91-4a72dc1c93c2.jpeg)

**Comment by theMarzon** [comment]
![image](https://user-images.githubusercontent.com/83615552/211135170-7fc27308-85dc-4c75-acc1-6dad91ae6ac4.png)
la tuya que se me abre jueperrra
